[package]
name = "text-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.1.0"
regex = "1"
tokio = { version = "1", features = ["full"] }
rayon = "1.5.3"
num_cpus = "1.13.1"